version: "2"
services:
  app:
    container_name: luglog
    env_file:
      - /var/www/luglog-api/environment/api-environment.env
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo0
  mongo0: # MongoDB replica set primary node
    hostname: mongo0
    container_name: mongo0
    build: ./docker/db
    volumes:
      - /var/www/luglog-api/db:/data/db
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--keyFile", "/tmp/luglogdatabase" ]
  mongo1: # Secondary node
    hostname: mongo1
    container_name: mongo1
    build: ./docker/db
    ports:
      - "27018:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--keyFile", "/tmp/luglogdatabase" ]
  mongo2: # Secondary node
    hostname: mongo2
    container_name: mongo2
    build: ./docker/db
    ports:
      - "27019:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--keyFile", "/tmp/luglogdatabase" ]
