const referralTypes = {
    CUSTOMER_TO_CUSTOMER: 'CUSTOMER_TO_CUSTOMER',
    REF_PARTNER_TO_CUSTOMER: 'REF_PARTNER_TO_CUSTOMER',
    REFERRAL_PARTNER_NON_PAYMENT: 'REFERRAL_PARTNER_NON_PAYMENT'
}

module.exports = {
    referralTypes
}